- hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.copy:
        src: tf
        dest: /tmp

    - ansible.builtin.tempfile:
        suffix: .tfplan
      register: plan_file

    - ansible.builtin.include_role:
        name: cloud.terraform_ops.module_plan_stash
      vars:
        module_plan_stash_operation: load
        module_plan_stash_plan_file_path: "{{ plan_file.path }}"

    - cloud.terraform.terraform:
        force_init: true
        project_path: /tmp/tf
        plan_file: "{{ plan_file.path }}"
