- hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.copy:
        src: tf
        dest: /tmp

    - ansible.builtin.tempfile:
        suffix: .tfplan
      register: plan_file

    - cloud.terraform.terraform:
        force_init: true
        project_path: /tmp/tf
        plan_file: "{{ plan_file.path }}"
      check_mode: true

    - cloud.terraform.plan_stash:
        path: "{{ plan_file.path }}"
      no_log: true
